name: 'sync_parent'
on: workflow_dispatch
  
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sdkrach/Dev-MavenParentUpdaterAction@main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}